# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  variables:
    IMAGE_NAME: 'cid-checker'
    PROJECT: 'filecoin'
    ENVIRONMENT: 'mainnet'
    SUB_ENV: 'glif'
    SHORT_REGION: 'apn1'

phases:
  install:
    commands:
      - echo Environment Variables
      - export BUILD_IMAGE_VERSION_TAG=$(cat ./release.yaml | cut -d ':' -f2)
      - printenv
#      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
#      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

#      - aws --version


      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com)

  pre_build:
    commands:
      - echo Build STARTED
      - docker build -t $IMAGE_NAME:$(echo $BUILD_IMAGE_VERSION_TAG) .
  build:
    commands:
      - echo Image built
      - echo Build STARTED

      - docker tag $IMAGE_NAME:$(echo $BUILD_IMAGE_VERSION_TAG) $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT-$ENVIRONMENT-$SHORT_REGION-$SUB_ENV-$IMAGE_NAME:$(echo $BUILD_IMAGE_VERSION_TAG)
#      - docker push ${CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT}-${ENVIRONMENT}-${SHORT_REGION}-${SUB_ENV}-${IMAGE_NAME}:$(echo $BUILD_IMAGE_VERSION_TAG)
