# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  variables:
    SHORT_REGION: 'apn1'
    DOCKERHUB_ORGANIZATION: 'protofire'
    HELM_VERSION: 'v3.1.0'
    DOCKERHUB_REPO_NAME: 'cid-checker'
    APP_VERSION: '0.1.3'
    NETWORK: 'calibration'
    KUBECTL_VERSION: 1.24.3
  secrets-manager:
    DOCKERHUB_USERNAME: "filecoin-mainnet-apn1-glif-dockerhub-glifio:username"
    DOCKERHUB_PASS: "filecoin-mainnet-apn1-glif-dockerhub-glifio:password"
    AWS_ACCESS_KEY_ID: "filecoin-dev-apn1-glif-codebuild-user:AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "filecoin-dev-apn1-glif-codebuild-user:AWS_SECRET_ACCESS_KEY"

phases:
  install:
    commands:
      - echo Environment Variables
      - printenv
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/${KUBECTL_VERSION}/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv kubectl /usr/bin/
      - aws eks --region $AWS_REGION update-kubeconfig --name $PROJECT-$ENVIRONMENT-$SHORT_REGION-$SUB_ENV-eks
      - wget https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
      - tar -xzvf helm-${HELM_VERSION}-linux-amd64.tar.gz
      - chmod +x ./linux-amd64/helm
      - mv ./linux-amd64/helm /usr/bin/helm

  pre_build:
    commands:
      - echo Build STARTED
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - kubectl get ns
      - make docker_build_all
      - docker tag cid-checker-frontend:latest $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-frontend
      - docker tag cid-checker-api:latest $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-backend
      - docker tag cid-checker-watcher:latest $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-watcher
      - docker push $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-frontend
      - docker push $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-backend
      - docker push $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-watcher
      - cd helm
      - helm upgrade --install cid-checker-$NETWORK . -f env-values/$NETWORK.yaml
