# Default values for CID.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

services:
  frontend:
    replicaCount: 1
    image:
      repository: protofire/cid-checker
      tag: 0.1.3-frontend
      pullPolicy: IfNotPresent
  backend:
    replicaCount: 1
    image:
      repository: protofire/cid-checker
      tag: 0.1.3-backend
      pullPolicy: IfNotPresent
    env:
      NODE_ENV: "production"
      CID_DB_NAME: "filecoindbspace06"
      CID_LOTUS_RPCURL: "https://calibration.node.glif.io/archive/lotus/rpc/v0"
      HEIGHT_ALARM_ALLOW_DIFF: "60"
  # Overrides the image tag whose default is the chart appVersion.
  mongo:
    image:
      repository: mongo
      tag: 5.0.4
      pullPolicy: IfNotPresent
    volumeSize: 30

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: filecoin.tools
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: cid.filecoin.tools
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# autoscaling:
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
